### ISSUE TITLE
Output the JSON format for the values in the following format

### ISSUE THREAD

**Issue by cherrera2001** [hashmapinc/nifi-opcua-bundle#21] opened 2017-10-10 01:49 UTC
In order for the SQL to be easily made via nifi, the JSON output should be formatted in the following way:
{
  "values": [
    {
      "id": "Sample.PumpPressure",
      "ts": "Doe",
      "vs": 23,
      "q": 1
    },
    {
      "id": "Sample.Torque",
      "ts": "Smith",
      "vs": 32,
      "q": 1
    }
  ]
}

JSON tag names should match the tag_data.sql table column name:
https://raw.githubusercontent.com/hashmapinc/Timeseries/master/persistence-plane/Config/Phoenix/tag_data.sql?token=AQCQkwnmSJV9HPqX6scq8bwt7UjaEGSuks5Z5nabwA%3D%3D

**Comment by ed3766** [comment] 2017-10-12 02:55
Duplicate of #23

**Closed** 2017-10-12 03:22 UTC
Labels: enhancement, review
